{
 "title": "NAT Instance",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Quick CPU/Qutas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{nat_instance=\"true\"}"
    }
   ]
  },
  {
   "title": "Connections utilization quota",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_connections_quota_utilization{nat_instance=\"true\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Connections quota utilization ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_connections_quota_utilization{nat_instance=\"true\"}",
     "legendFormat": "Utilization %"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(network_received_bytes{nat_instance=\"true\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(network_sent_bytes{nat_instance=\"true\"})",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(network_received_packets{nat_instance=\"true\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(network_sent_packets{nat_instance=\"true\"})",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cpu_utilization{nat_instance=\"true\"}",
       "legendFormat": "Core {{cpu_name}}"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cpu_usage{nat_instance=\"true\"}",
       "legendFormat": "Usage %"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "disk_read_ops{nat_instance=\"true\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "disk_write_ops{nat_instance=\"true\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "disk_read_bytes{nat_instance=\"true\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "disk_write_bytes{nat_instance=\"true\"}",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  }
 ]
}